### ISSUE TITLE
Osiris does not support multi-part form uploads

### ISSUE THREAD

**Issue by v79** [cjkent/osiris#520]
I've noticed that Osiris does not handle mutli-part form uploads - is that by design or something which could be added in the future?

In `Http.kt`, the class `ContentType` throws and IllegalArgumentException when presented with `Content-Type: multipart/form-data; boundary=-----` as it defintely doesn't match the allowed Regex.

**Comment by cjkent** [comment]
It should work at the moment if you configure `multipart/form-data` to be handled as binary. That is done by default in 1.5.3 so if you upgrade you won't have to change anything else.

I'll fix `ContentType` in the next release, but it's only a convenience so you don't have to use it.

Osiris doesn't have any built-in support for parsing multipart form data, but there are libraries availalbe for that so there's no point reinventing the wheel.

Here's an example of using [Apache Commons FileUpload](http://commons.apache.org/proper/commons-fileupload/) to parse the body.

```kotlin
post("/upload") { req ->
    val inputStream = ByteArrayInputStream(req.body())
    // Parse the boundary out of the Content-Type header
    // ContentType will handle this when it supports multipart form data
    val contentType = req.headers["Content-Type"]
    val boundaryStart = contentType.indexOf("boundary=") + 9
    val boundary = contentType.substring(boundaryStart)
    val boundaryBytes = boundary.toByteArray()
    val multipartStream = MultipartStream(inputStream, boundaryBytes, 2048, null)
    var nextPart = multipartStream.skipPreamble()
    while (nextPart) {
        val header = multipartStream.readHeaders()
        // Read the body and do something with it
        multipartStream.readBodyData(...)
        nextPart = multipartStream.readBoundary()
    }
}
```

It's worth noting that AWS Lambda has a hard limit of 6MB for the request size so uploading large files won't work.
