### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by cjkent** [cjkent/osiris#72]
Need to support the OPTIONS method for pre-flight checks. Probably returning static values for the `Access-Control-*` headers.

Need to add `Access-Control-Allow-Origin` header to regular methods. This could be a filter.

At what level should this be applied? Whole API? Subset of endpoints (like an `auth` block)?

Is there ever a case where the user would need to run code to generate the headers? Seems unlikely.

Syntax options:

```kotlin
cors {
    // properties specifying CORS headers

    get("/foo") {
        ...
    }
}
```

```kotlin
cors("/foo/*) {
    // properties specifying CORS headers
}

get("/foo") {
    ...
}
```

https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html

**Comment by cjkent** [comment]
Hi Konstantinos,

You can use a filter to add CORS headers. I have a very simple example working with the following filter:

```kotlin
filter { req, handler ->
    if (req.method == HttpMethod.OPTIONS) {
        // for an OPTIONS request, return a response containing the CORS headers
        req.responseBuilder()
            .header("Access-Control-Allow-Methods", "*")
            .header("Access-Control-Allow-Headers", "*")
            .header("Access-Control-Allow-Origin", "*")
            .build()
    } else {
        // for non-OPTIONS requests, pass the request on for processing, and then add the CORS header to the response
        handler(req).withHeader("Access-Control-Allow-Origin", "*")
    }
}
```

There are other ways you can avoid CORS issues. The simplest is to serve your static files using Osiris so the origin of the page is the same as the origin of the request. See [here](https://github.com/cjkent/osiris/wiki/Static-Files) for details. This doesn't work for all cases, for example there's no way to allow deep linking into a single page app using this approach.

The other thing you can do is to use CloudFront to serve your site. You need a CloudFront distribution with two origins, one for the S3 bucket containing your static files and the other pointing to your API Gateway REST API. This is the most flexible way but also the most complicated.

**Comment by cjkent** [comment]
Enabling CORS for a "simple" request can be done easily with a filter. Roughly speaking, a "simple" request is a GET request or a POST request with a content type of `text/plain` or form data. See [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/how-to-cors.html) for a full definition of a simple request.

```kotlin
filter { req, handler ->
    // pass the request on for processing, and then add the CORS header to the response
    handler(req).withHeader("Access-Control-Allow-Origin", "*")
}
```

However, most real APIs will need to support non-simple requests, e.g. POST requests containing JSON. In this case, the browser makes a so-called "pre-flight" request; this is an OPTIONS request to the endpoint to check if the cross-origin request is allowed. If the response contains the correct CORS headers and the caller's origin is allowed, then the browser makes the request.

Unfortunately Osiris doesn't have very good support for non-simple CORS request. If you only need to enable CORS for a few endopints, this can be done by explicitly handling the OPTIONS request:

```kotlin
options("/foo") { req ->
    req.responseBuilder()
        .header("Access-Control-Allow-Methods", "*")
        .header("Access-Control-Allow-Headers", "*")
        .header("Access-Control-Allow-Origin", "*")
        .build()
}
```

Obviously this is isn't a great for a large API where every endpoint needs CORS enabled.

I'm thinking about how to support non-simple CORS requests for the whole API, but unfortunately this is your only solution for now.

**Comment by cjkent** [comment]
I've been thinking about this, and I have a rough design. This is pure vapourware ATM, I haven't started implementing anything, and if I do it might turn out different in the end. But please let me know if it makes sense, or if you think it doesn't, or if you have an alternative suggestion.

For cases where you only need to support CORS for a limited number of endpoints then you can just handle the requests and insert the headers normally.

For simple requests:
```kotlin
get("foo") { req ->
    req.responseBuilder()
        .header("Access-Control-Allow-Origin", "*")
        .build("hello, world!")
}
```
For non-simple requests you would have to handle the OPTIONS pre-flight request explicitly:
```kotlin
options("/foo") { req ->
    req.responseBuilder()
        .header("Access-Control-Allow-Methods", "*")
        .header("Access-Control-Allow-Headers", "*")
        .header("Access-Control-Allow-Origin", "*")
        .build()
}
```
For cases where you want to support CORS for a large number of endpoints or the whole API, then there would be a different approach. There would be a `cors` flag (boolean, or possibly an enum) that could be specified at the level of the API or on each endpoint supporting CORS:
```kotlin
// the whole API supprts CORS
val api = api<MyComponentProvider>(cors = true) {
    ...
}
```
or per-endpoint
```kotlin
get("/foo", cors = true) { req ->
    ...
}
```
When using the `cors` flag, you would also need to provide a `cors` block in the API definition that returns an object containing the CORS headers:
```kotlin
cors { req ->
    CorsHeaders(
        allowMethods = setOf(HttpMethod.GET, HttpMethod.POST),
        allowHeaders = setOf(HttpHeaders.CONTENT_TYPE),
        allowOrigin = setOf("*")
    )
}
```
This block would be invoked for every request to an endpoint with `cors = true`. It can examine the request when deciding what headers to return, or it could simply return the same set of headers for ever CORS request.

**Comment by kmponis** [comment]
Hi Chris,

Thank you very much for the update.

Yes the solution with the cors flag sounds fantastic. The cors flag is going to apply for both simple and non-simple endpoint right? 

That will make the use of cors so much easier. Having a flag and apply it wherever is needed.

**Comment by cjkent** [comment]
v1.5.0 has built-in CORS support see the [wiki page](https://github.com/cjkent/osiris/wiki/CORS) or the [example project](https://github.com/cjkent/osiris-examples/tree/master/cors) for details.
